<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<RootNamespace>SidebarDiagnostics</RootNamespace>
		<AssemblyName>SidebarDiagnostics</AssemblyName>
		<ApplicationIcon>Sidebar.ico</ApplicationIcon>
		<StartupObject>SidebarDiagnostics.App</StartupObject>
		<ApplicationManifest>Properties\app.manifest</ApplicationManifest>
		<ApplicationVersion>1.3.0.0</ApplicationVersion>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<None Include="ChangeLog.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Sidebar.ico" />
		<Resource Include="Settings.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
		<PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
		<PackageReference Include="TaskScheduler" Version="2.12.2" />
		<PackageReference Include="Mono.Cecil" Version="0.11.6" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
		<PackageReference Include="SharpCompress" Version="0.47.4" />
		<PackageReference Include="Splat" Version="19.3.1" />
		<PackageReference Include="Splat.Builder" Version="19.3.1" />
		<PackageReference Include="Splat.Core" Version="19.3.1" />
		<PackageReference Include="Splat.Logging" Version="19.3.1" />
		<PackageReference Include="System.Reactive" Version="6.1.0" />
		<PackageReference Include="WPF-UI" Version="4.3.0" />
	</ItemGroup>

</Project>
